UT Changes
ResearchCollectionsAndPreservation/scsb-etl pull request #34
Opened 2020-09-02 13:06 UTC by JancyRoachR

2020-09-03 07:26 UTC, rajeshbabuk approved these changes
Good to merge

2020-09-07 05:44 UTC, srinduri04 requested changes
Please make the changes as requested.

2020-09-07 06:56 UTC, JancyRoachR commented
Changes are made as requested.

2020-09-08 06:25 UTC, srinduri04 approved these changes
Approved

2020-09-08 06:28 UTC, srinduri04 approved these changes
Approved

2020-09-08 06:29 UTC, merged